import {
  AlertCircle,
  AlertTriangle,
  CreditCard,
  DollarSign,
  Download,
  FileText,
  Link2,
  LogIn,
  Mail,
  MessageSquare,
  Package,
  PackageMinus,
  PackagePlus,
  Pencil,
  Plus,
  RefreshCw,
  RotateCcw,
  Settings,
  ShoppingCart,
  Store,
  Tag,
  Trash2,
  TrendingDown,
  Truck,
  Upload,
  UserPlus,
} from "lucide-react";

import type { EventTypeConfig } from "@/@types/Modules/Core/DesignSystem/event-type";

export const EVENT_TYPES = {
  atualizacao: {
    icon: DollarSign,
    colorClassName: "text-status-purple",
    label: "Atualização de preço",
    usage: "Preço de venda alterado (manual ou por regra automática).",
  },
  sync: {
    icon: RefreshCw,
    colorClassName: "text-info",
    label: "Sincronização",
    usage: "Dados enviados ao e-commerce ou integração com sucesso.",
  },
  "erro-sync": {
    icon: AlertCircle,
    colorClassName: "text-destructive",
    label: "Erro de sincronização",
    usage: "Falha ao sincronizar com o e-commerce, exige ação do operador.",
  },
  concorrente: {
    icon: TrendingDown,
    colorClassName: "text-warning",
    label: "Concorrente",
    usage: "Monitoramento detectou preço de concorrente.",
  },
  criacao: {
    icon: Plus,
    colorClassName: "text-success",
    label: "Criação",
    usage: "Registro criado no sistema (produto, regra, pedido).",
  },
  edicao: {
    icon: Pencil,
    colorClassName: "text-muted-foreground",
    label: "Edição",
    usage: "Campo editado manualmente, sem mudança de preço.",
  },
  exclusao: {
    icon: Trash2,
    colorClassName: "text-destructive",
    label: "Exclusão",
    usage: "Registro removido ou desativado.",
  },
  pedido: {
    icon: ShoppingCart,
    colorClassName: "text-info",
    label: "Pedido",
    usage: "Novo pedido recebido ou mudança de status do pedido.",
  },
  pagamento: {
    icon: CreditCard,
    colorClassName: "text-success",
    label: "Pagamento",
    usage: "Pagamento aprovado, confirmado ou recebido.",
  },
  estorno: {
    icon: RotateCcw,
    colorClassName: "text-warning",
    label: "Estorno / devolução",
    usage: "Pagamento estornado ou mercadoria devolvida.",
  },
  "entrada-estoque": {
    icon: PackagePlus,
    colorClassName: "text-success",
    label: "Entrada de estoque",
    usage: "Recebimento de mercadoria ou ajuste positivo.",
  },
  "saida-estoque": {
    icon: PackageMinus,
    colorClassName: "text-status-orange",
    label: "Saída de estoque",
    usage: "Baixa por venda, perda ou ajuste negativo.",
  },
  estoque: {
    icon: Package,
    colorClassName: "text-info",
    label: "Estoque",
    usage: "Inventário, contagem ou mudança genérica de estoque.",
  },
  "nota-fiscal": {
    icon: FileText,
    colorClassName: "text-status-purple",
    label: "Nota fiscal",
    usage: "NF-e emitida, cancelada ou rejeitada pela SEFAZ.",
  },
  entrega: {
    icon: Truck,
    colorClassName: "text-status-teal",
    label: "Entrega",
    usage: "Expedição, em trânsito ou entrega concluída.",
  },
  importacao: {
    icon: Upload,
    colorClassName: "text-info",
    label: "Importação",
    usage: "Planilha ou arquivo importado ao sistema.",
  },
  exportacao: {
    icon: Download,
    colorClassName: "text-info",
    label: "Exportação",
    usage: "Relatório ou arquivo exportado.",
  },
  integracao: {
    icon: Link2,
    colorClassName: "text-status-teal",
    label: "Integração",
    usage: "Conexão de marketplace, webhook ou API externa.",
  },
  ecommerce: {
    icon: Store,
    colorClassName: "text-status-purple",
    label: "E-commerce",
    usage: "Evento do canal de venda online (vínculo, publicação).",
  },
  etiqueta: {
    icon: Tag,
    colorClassName: "text-status-orange",
    label: "Etiqueta / promoção",
    usage: "Tag aplicada, promoção iniciada ou encerrada.",
  },
  alerta: {
    icon: AlertTriangle,
    colorClassName: "text-warning",
    label: "Alerta",
    usage: "Regra de monitoramento disparada (margem, ruptura).",
  },
  usuario: {
    icon: UserPlus,
    colorClassName: "text-success",
    label: "Usuário",
    usage: "Usuário criado, convidado ou permissão alterada.",
  },
  acesso: {
    icon: LogIn,
    colorClassName: "text-muted-foreground",
    label: "Acesso",
    usage: "Login, logout ou troca de senha.",
  },
  email: { icon: Mail, colorClassName: "text-info", label: "E-mail", usage: "Notificação enviada por e-mail." },
  comentario: {
    icon: MessageSquare,
    colorClassName: "text-muted-foreground",
    label: "Comentário",
    usage: "Anotação interna registrada por um usuário.",
  },
  configuracao: {
    icon: Settings,
    colorClassName: "text-muted-foreground",
    label: "Configuração",
    usage: "Parâmetro do sistema alterado.",
  },
} as const satisfies Record<string, EventTypeConfig>;

export const FALLBACK_EVENT_TYPE = "atualizacao" satisfies keyof typeof EVENT_TYPES;
