import type { ApiEndpoint } from "@/@types/Modules/Core/Api/api-endpoint";

export const API_ENDPOINTS = {
  auth: {
    login: { method: "POST", path: "/auth/login", summary: "Primeira etapa do login: e-mail e senha", isPublic: true },
    verify: {
      method: "POST",
      path: "/auth/login/verify",
      summary: "Segunda etapa do login: código do e-mail",
      isPublic: true,
    },
    resend: { method: "POST", path: "/auth/login/resend", summary: "Reenvia o código do login", isPublic: true },
    refresh: { method: "POST", path: "/auth/refresh", summary: "Renova a sessão", isPublic: true },
    logout: { method: "POST", path: "/auth/logout", summary: "Sai do sistema", isPublic: true },
    forgotPassword: { method: "POST", path: "/auth/password/forgot", summary: "Esqueci a senha", isPublic: true },
    resetPassword: {
      method: "POST",
      path: "/auth/password/reset",
      summary: "Cria a nova senha pelo link",
      isPublic: true,
    },
    getInvite: { method: "GET", path: "/auth/invites/{token}", summary: "Confere um link de convite", isPublic: true },
    acceptInvite: {
      method: "POST",
      path: "/auth/invites/accept",
      summary: "Aceita o convite e cria a senha",
      isPublic: true,
    },
  },
  account: {
    get: { method: "GET", path: "/auth/me", summary: "Dados do usuário logado" },
    update: { method: "PUT", path: "/auth/me", summary: "Atualiza o próprio cadastro" },
    changePassword: { method: "PUT", path: "/auth/me/password", summary: "Troca a própria senha" },
    setPin: { method: "PUT", path: "/auth/me/pin", summary: "Cria ou troca um PIN de segurança" },
  },
  permissions: {
    menu: { method: "GET", path: "/permissions/menu", summary: "Menu do usuário logado" },
    components: {
      method: "GET",
      path: "/permissions/{code}/components",
      summary: "Componentes de uma página para o usuário logado",
    },
  },
  preferences: {
    list: { method: "GET", path: "/auth/me/preferences", summary: "Lista as preferências do usuário logado" },
    get: { method: "GET", path: "/auth/me/preferences/{key}", summary: "Lê uma preferência do usuário logado" },
    save: { method: "PUT", path: "/auth/me/preferences/{key}", summary: "Salva uma preferência do usuário logado" },
    remove: {
      method: "DELETE",
      path: "/auth/me/preferences/{key}",
      summary: "Remove uma preferência do usuário logado",
    },
  },
  users: {
    list: { method: "GET", path: "/users", summary: "Lista os usuários", page: "usuarios" },
    get: { method: "GET", path: "/users/{id}", summary: "Detalhe de um usuário", page: "usuarios" },
    update: {
      method: "PUT",
      path: "/users/{id}",
      summary: "Edita um usuário",
      page: "usuarios",
      component: "usuarios.editarusuarios",
    },
    deactivate: {
      method: "POST",
      path: "/users/{id}/deactivate",
      summary: "Desativa um usuário",
      page: "usuarios",
      component: "usuarios.desativarusuario",
    },
    activate: {
      method: "POST",
      path: "/users/{id}/activate",
      summary: "Reativa um usuário",
      page: "usuarios",
      component: "usuarios.desativarusuario",
    },
    resetPassword: {
      method: "POST",
      path: "/users/{id}/password-reset",
      summary: "Redefine a senha de um usuário",
      page: "usuarios",
      component: "usuarios.redefinirsenhas",
    },
    viewAs: {
      method: "POST",
      path: "/users/{id}/view-as",
      summary: "Visualiza o sistema como um usuário",
      page: "usuarios",
      component: "usuarios.visualizarcomo",
    },
    activity: {
      method: "GET",
      path: "/users/{id}/activity",
      summary: "Log de atividades do usuário",
      page: "usuarios",
      component: "usuarios.verlogs",
    },
  },
  invites: {
    create: {
      method: "POST",
      path: "/users/invites",
      summary: "Convida um usuário",
      page: "usuarios",
      component: "usuarios.convidarusuarios",
    },
    list: {
      method: "GET",
      path: "/users/invites",
      summary: "Lista os convites",
      page: "usuarios",
      component: "usuarios.verconvites",
    },
    resend: {
      method: "POST",
      path: "/users/invites/{userId}/resend",
      summary: "Reenvia um convite",
      page: "usuarios",
      component: "convites.reenviar",
    },
    link: {
      method: "GET",
      path: "/users/invites/{userId}/link",
      summary: "Copia o link do convite",
      page: "usuarios",
      component: "convites.copiarlink",
    },
    cancel: {
      method: "DELETE",
      path: "/users/invites/{userId}",
      summary: "Cancela um convite",
      page: "usuarios",
      component: "convites.cancelar",
    },
  },
  profiles: {
    list: { method: "GET", path: "/profiles", summary: "Lista os perfis", page: "usuarios" },
    create: {
      method: "POST",
      path: "/profiles",
      summary: "Cria um perfil",
      page: "usuarios",
      component: "perfis.criarperfil",
    },
    get: { method: "GET", path: "/profiles/{id}", summary: "Detalhe de um perfil", page: "usuarios" },
    update: {
      method: "PUT",
      path: "/profiles/{id}",
      summary: "Edita um perfil",
      page: "usuarios",
      component: "perfis.editarperfil",
    },
    remove: {
      method: "DELETE",
      path: "/profiles/{id}",
      summary: "Remove um perfil",
      page: "usuarios",
      component: "perfis.removerperfil",
    },
    catalog: { method: "GET", path: "/profiles/catalog", summary: "Catálogo de permissões", page: "usuarios" },
    updatePermissions: {
      method: "PUT",
      path: "/profiles/{id}/permissions",
      summary: "Troca as permissões de um perfil",
      page: "usuarios",
      component: "perfis.editarpermissoes",
    },
    viewAs: {
      method: "POST",
      path: "/profiles/{id}/view-as",
      summary: "Visualiza o sistema como um perfil",
      page: "usuarios",
      component: "perfis.visualizarcomo",
    },
  },
  companies: {
    list: { method: "GET", path: "/companies", summary: "Lista as empresas", page: "empresas", platformScope: true },
    create: {
      method: "POST",
      path: "/companies",
      summary: "Cria uma empresa",
      page: "empresas",
      component: "empresas.criarempresa",
      platformScope: true,
    },
    get: {
      method: "GET",
      path: "/companies/{id}",
      summary: "Detalhe de uma empresa",
      page: "empresas",
      platformScope: true,
    },
    update: {
      method: "PUT",
      path: "/companies/{id}",
      summary: "Edita uma empresa",
      page: "empresas",
      component: "empresas.editarempresa",
      platformScope: true,
    },
    mine: { method: "GET", path: "/companies/me", summary: "Minha empresa" },
    suspend: {
      method: "POST",
      path: "/companies/{id}/suspend",
      summary: "Suspende uma empresa",
      page: "empresas",
      component: "empresas.suspenderempresa",
      platformScope: true,
    },
    activate: {
      method: "POST",
      path: "/companies/{id}/activate",
      summary: "Reativa uma empresa",
      page: "empresas",
      component: "empresas.suspenderempresa",
      platformScope: true,
    },
  },
  plans: {
    list: { method: "GET", path: "/plans", summary: "Lista os planos", page: "planos", platformScope: true },
    create: {
      method: "POST",
      path: "/plans",
      summary: "Cria um plano",
      page: "planos",
      component: "planos.criarplano",
      platformScope: true,
    },
    get: { method: "GET", path: "/plans/{id}", summary: "Detalhe de um plano", page: "planos", platformScope: true },
    update: {
      method: "PUT",
      path: "/plans/{id}",
      summary: "Edita um plano",
      page: "planos",
      component: "planos.editarplano",
      platformScope: true,
    },
    remove: {
      method: "DELETE",
      path: "/plans/{id}",
      summary: "Remove um plano",
      page: "planos",
      component: "planos.removerplano",
      platformScope: true,
    },
    updatePermissions: {
      method: "PUT",
      path: "/plans/{id}/permissions",
      summary: "Troca as páginas e componentes de um plano",
      page: "planos",
      component: "planos.editarpermissoes",
      platformScope: true,
    },
  },
  communication: {
    get: {
      method: "GET",
      path: "/communication",
      summary: "Comunicação: cabeçalho, rodapé e e-mails disparados",
      page: "comunicacao",
    },
    getNotification: {
      method: "GET",
      path: "/communication/notifications/{key}",
      summary: "Detalhe de uma notificação",
      page: "comunicacao",
    },
    update: {
      method: "PUT",
      path: "/communication/notifications/{key}",
      summary: "Personaliza uma notificação",
      page: "comunicacao",
      component: "comunicacao.editaremails",
    },
    saveAsDefault: {
      method: "POST",
      path: "/communication/notifications/{key}/default",
      summary: "Salva o texto atual como padrão da empresa",
      page: "comunicacao",
      component: "comunicacao.editaremails",
    },
    restore: {
      method: "POST",
      path: "/communication/notifications/{key}/restore",
      summary: "Restaura o padrão",
      page: "comunicacao",
      component: "comunicacao.editaremails",
    },
    setStatus: {
      method: "PUT",
      path: "/communication/notifications/{key}/status",
      summary: "Liga ou desliga uma notificação",
      page: "comunicacao",
      component: "comunicacao.editaremails",
    },
    preview: {
      method: "POST",
      path: "/communication/notifications/{key}/preview",
      summary: "Pré-visualiza uma notificação",
      page: "comunicacao",
    },
    sendTest: {
      method: "POST",
      path: "/communication/notifications/{key}/test",
      summary: "Envia um e-mail de teste",
      page: "comunicacao",
      component: "comunicacao.enviarteste",
    },
  },
  emailIntegrations: {
    providers: {
      method: "GET",
      path: "/integrations/email/providers",
      summary: "Catálogo de envio de e-mail",
      page: "comunicacao",
    },
    list: {
      method: "GET",
      path: "/integrations/email",
      summary: "Lista as conexões de envio de e-mail",
      page: "comunicacao",
    },
    create: {
      method: "POST",
      path: "/integrations/email",
      summary: "Cria uma conexão de envio de e-mail",
      page: "comunicacao",
      component: "comunicacao.configurarenvio",
    },
    get: {
      method: "GET",
      path: "/integrations/email/{id}",
      summary: "Detalhe de uma conexão de envio de e-mail",
      page: "comunicacao",
    },
    update: {
      method: "PUT",
      path: "/integrations/email/{id}",
      summary: "Edita uma conexão de envio de e-mail",
      page: "comunicacao",
      component: "comunicacao.configurarenvio",
    },
    remove: {
      method: "DELETE",
      path: "/integrations/email/{id}",
      summary: "Remove uma conexão de envio de e-mail",
      page: "comunicacao",
      component: "comunicacao.configurarenvio",
    },
  },
  ecommerceIntegrations: {
    providers: {
      method: "GET",
      path: "/integrations/ecommerce/providers",
      summary: "Catálogo de e-commerce",
      page: "ecommerces",
    },
    list: {
      method: "GET",
      path: "/integrations/ecommerce",
      summary: "Lista as conexões de e-commerce",
      page: "ecommerces",
    },
    create: {
      method: "POST",
      path: "/integrations/ecommerce",
      summary: "Cria uma conexão de e-commerce",
      page: "ecommerces",
      component: "ecommerces.conectar",
    },
    get: {
      method: "GET",
      path: "/integrations/ecommerce/{id}",
      summary: "Detalhe de uma conexão de e-commerce",
      page: "ecommerces",
    },
    update: {
      method: "PUT",
      path: "/integrations/ecommerce/{id}",
      summary: "Edita uma conexão de e-commerce",
      page: "ecommerces",
      component: "ecommerces.editar",
    },
    remove: {
      method: "DELETE",
      path: "/integrations/ecommerce/{id}",
      summary: "Remove uma conexão de e-commerce",
      page: "ecommerces",
      component: "ecommerces.remover",
    },
  },
  aiIntegrations: {
    providers: { method: "GET", path: "/integrations/ai/providers", summary: "Catálogo de IA", page: "ia" },
    list: { method: "GET", path: "/integrations/ai", summary: "Lista as conexões de IA", page: "ia" },
    create: {
      method: "POST",
      path: "/integrations/ai",
      summary: "Cria uma conexão de IA",
      page: "ia",
      component: "ia.conectar",
    },
    get: { method: "GET", path: "/integrations/ai/{id}", summary: "Detalhe de uma conexão de IA", page: "ia" },
    update: {
      method: "PUT",
      path: "/integrations/ai/{id}",
      summary: "Edita uma conexão de IA",
      page: "ia",
      component: "ia.editar",
    },
    remove: {
      method: "DELETE",
      path: "/integrations/ai/{id}",
      summary: "Remove uma conexão de IA",
      page: "ia",
      component: "ia.remover",
    },
  },
  supplierIntegrations: {
    providers: {
      method: "GET",
      path: "/integrations/suppliers/providers",
      summary: "Catálogo de fornecedores",
      page: "fornecedores",
    },
    list: {
      method: "GET",
      path: "/integrations/suppliers",
      summary: "Lista as conexões de fornecedores",
      page: "fornecedores",
    },
    create: {
      method: "POST",
      path: "/integrations/suppliers",
      summary: "Cria uma conexão de fornecedores",
      page: "fornecedores",
      component: "fornecedores.conectar",
    },
    get: {
      method: "GET",
      path: "/integrations/suppliers/{id}",
      summary: "Detalhe de uma conexão de fornecedores",
      page: "fornecedores",
    },
    update: {
      method: "PUT",
      path: "/integrations/suppliers/{id}",
      summary: "Edita uma conexão de fornecedores",
      page: "fornecedores",
      component: "fornecedores.editar",
    },
    remove: {
      method: "DELETE",
      path: "/integrations/suppliers/{id}",
      summary: "Remove uma conexão de fornecedores",
      page: "fornecedores",
      component: "fornecedores.remover",
    },
  },
  supplierProducts: {
    list: {
      method: "GET",
      path: "/suppliers/products",
      summary: "Lista o catálogo dos fornecedores",
      page: "fornecedores",
      component: "fornecedores.vercatalogo",
    },
  },
  aiTasks: {
    list: { method: "GET", path: "/ai/tasks", summary: "Lista as tarefas de IA" },
    generate: { method: "POST", path: "/ai/tasks/{key}/generate", summary: "Gera conteúdo com IA para uma tarefa" },
  },
  auditLogs: {
    list: { method: "GET", path: "/audit-logs", summary: "Lista a auditoria", page: "auditoria" },
    get: { method: "GET", path: "/audit-logs/{id}", summary: "Detalhe de um registro de auditoria", page: "auditoria" },
  },
} as const satisfies Record<string, Record<string, ApiEndpoint>>;
