import type { StateCode, StateTile } from "@/@types/Modules/VisaoGeral/Dashboard/sales-breakdown";

export const BRAZIL_STATE_CODES = [
  "AC",
  "AL",
  "AP",
  "AM",
  "BA",
  "CE",
  "DF",
  "ES",
  "GO",
  "MA",
  "MT",
  "MS",
  "MG",
  "PA",
  "PB",
  "PR",
  "PE",
  "PI",
  "RJ",
  "RN",
  "RS",
  "RO",
  "RR",
  "SC",
  "SP",
  "SE",
  "TO",
] as const;

export const BRAZIL_STATE_NAMES = {
  AC: "Acre",
  AL: "Alagoas",
  AP: "Amapá",
  AM: "Amazonas",
  BA: "Bahia",
  CE: "Ceará",
  DF: "Distrito Federal",
  ES: "Espírito Santo",
  GO: "Goiás",
  MA: "Maranhão",
  MT: "Mato Grosso",
  MS: "Mato Grosso do Sul",
  MG: "Minas Gerais",
  PA: "Pará",
  PB: "Paraíba",
  PR: "Paraná",
  PE: "Pernambuco",
  PI: "Piauí",
  RJ: "Rio de Janeiro",
  RN: "Rio Grande do Norte",
  RS: "Rio Grande do Sul",
  RO: "Rondônia",
  RR: "Roraima",
  SC: "Santa Catarina",
  SP: "São Paulo",
  SE: "Sergipe",
  TO: "Tocantins",
} as const satisfies Record<StateCode, string>;

export const BRAZIL_STATE_TILES = [
  { code: "RR", row: 0, column: 2 },
  { code: "AP", row: 0, column: 4 },
  { code: "AM", row: 1, column: 1 },
  { code: "PA", row: 1, column: 3 },
  { code: "MA", row: 1, column: 4 },
  { code: "CE", row: 1, column: 5 },
  { code: "RN", row: 1, column: 6 },
  { code: "AC", row: 2, column: 0 },
  { code: "RO", row: 2, column: 1 },
  { code: "MT", row: 2, column: 2 },
  { code: "TO", row: 2, column: 3 },
  { code: "PI", row: 2, column: 4 },
  { code: "PE", row: 2, column: 5 },
  { code: "PB", row: 2, column: 6 },
  { code: "MS", row: 3, column: 2 },
  { code: "GO", row: 3, column: 3 },
  { code: "DF", row: 3, column: 4 },
  { code: "BA", row: 3, column: 5 },
  { code: "AL", row: 3, column: 6 },
  { code: "SP", row: 4, column: 3 },
  { code: "MG", row: 4, column: 4 },
  { code: "ES", row: 4, column: 5 },
  { code: "SE", row: 4, column: 6 },
  { code: "PR", row: 5, column: 3 },
  { code: "RJ", row: 5, column: 4 },
  { code: "SC", row: 6, column: 3 },
  { code: "RS", row: 7, column: 3 },
] as const satisfies readonly StateTile[];

export const STATE_GRID_COLUMNS = 7;
