export const CODE_CIRCLE_RADIUS_PX = 36;
export const CODE_CIRCLE_START_ANGLE_DEGREES = -90;
export const CODE_CIRCLE_SLOT_SCALE = 0.6;

export const LOGIN_SUCCESS_SLOTS_DURATION_SECONDS = 1.4;
export const LOGIN_SUCCESS_CIRCLE_AT = 0.25;
export const LOGIN_SUCCESS_SPIN_END_AT = 0.7;
export const LOGIN_SUCCESS_SPIN_DEGREES = 360;
export const LOGIN_SUCCESS_DIGITS_FADE_AT = 0.15;

export const LOGIN_SUCCESS_CHECK_PATH = "M7 12.5l3.5 3.5L17 9";
export const LOGIN_SUCCESS_CHECK_STROKE_WIDTH = 2.5;
export const LOGIN_SUCCESS_CHECK_DELAY_SECONDS = 1.6;
export const LOGIN_SUCCESS_CHECK_DRAW_SECONDS = 0.35;
export const LOGIN_SUCCESS_HOLD_MS = 400;
