import type { HttpMethod } from "@/@types/Modules/Core/Api/api-endpoint";
import type { ApiEndpointKey } from "@/@types/Modules/Core/Api/api-endpoint-key";
import type { BadgeTone } from "@/@types/Modules/Core/DesignSystem/badge-tone";

export const SHELL_ENDPOINT_KEYS: readonly ApiEndpointKey[] = [
  "auth.refresh",
  "auth.logout",
  "permissions.mine",
  "companies.mine",
  "companies.list",
];

export const PAGE_ENDPOINT_KEYS: Readonly<Record<string, readonly ApiEndpointKey[]>> = {
  "/login": ["auth.login", "auth.verify", "auth.resend"],
  "/esqueci-senha": ["auth.forgotPassword"],
  "/redefinir-senha": ["auth.resetPassword"],
  "/convite": ["auth.getInvite", "auth.acceptInvite"],
  "/minha-conta": ["account.get", "account.update", "account.changePassword", "account.setPin"],
  "/administracao/usuarios": [
    "users.list",
    "users.get",
    "users.update",
    "users.deactivate",
    "users.activate",
    "users.resetPassword",
    "users.viewAs",
    "users.activity",
    "invites.create",
    "invites.list",
    "invites.resend",
    "invites.link",
    "invites.cancel",
    "profiles.list",
    "profiles.get",
    "profiles.catalog",
    "profiles.create",
    "profiles.update",
    "profiles.updatePermissions",
    "profiles.remove",
    "profiles.viewAs",
  ],
  "/administracao/comunicacao": [
    "communication.get",
    "communication.getNotification",
    "communication.update",
    "communication.preview",
    "communication.saveAsDefault",
    "communication.restore",
    "communication.setStatus",
    "communication.sendTest",
    "emailIntegrations.providers",
    "emailIntegrations.list",
    "emailIntegrations.get",
    "emailIntegrations.create",
    "emailIntegrations.update",
    "emailIntegrations.remove",
  ],
  "/administracao/ecommerce": [
    "ecommerceIntegrations.providers",
    "ecommerceIntegrations.list",
    "ecommerceIntegrations.get",
    "ecommerceIntegrations.create",
    "ecommerceIntegrations.update",
    "ecommerceIntegrations.remove",
  ],
  "/administracao/agentes-ia": [
    "aiIntegrations.providers",
    "aiIntegrations.list",
    "aiIntegrations.get",
    "aiIntegrations.create",
    "aiIntegrations.update",
    "aiIntegrations.remove",
  ],
  "/administracao/fornecedores": [
    "supplierIntegrations.providers",
    "supplierIntegrations.list",
    "supplierIntegrations.get",
    "supplierIntegrations.create",
    "supplierIntegrations.update",
    "supplierIntegrations.remove",
    "supplierProducts.list",
  ],
  "/administracao/auditoria": ["auditLogs.list", "auditLogs.get"],
  "/plataforma/empresas": [
    "companies.get",
    "companies.create",
    "companies.update",
    "companies.suspend",
    "companies.activate",
    "plans.list",
  ],
  "/plataforma/planos": [
    "plans.list",
    "plans.get",
    "plans.create",
    "plans.update",
    "plans.updatePermissions",
    "plans.remove",
    "profiles.catalog",
  ],
};

export const HTTP_METHOD_TONE: Record<HttpMethod, BadgeTone> = {
  GET: "info",
  POST: "success",
  PUT: "warning",
  DELETE: "destructive",
};
